/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as PedidoRouteImport } from './routes/pedido'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CardapioRouteImport } from './routes/cardapio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminCardapioRouteImport } from './routes/admin.cardapio'

const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoRoute = PedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioRoute = CardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/admin/financeiro',
  path: '/admin/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCardapioRoute = AdminCardapioRouteImport.update({
  id: '/admin/cardapio',
  path: '/admin/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/conta': typeof ContaRoute
  '/login': typeof LoginRoute
  '/pedido': typeof PedidoRoute
  '/pedidos': typeof PedidosRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/conta': typeof ContaRoute
  '/login': typeof LoginRoute
  '/pedido': typeof PedidoRoute
  '/pedidos': typeof PedidosRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/conta': typeof ContaRoute
  '/login': typeof LoginRoute
  '/pedido': typeof PedidoRoute
  '/pedidos': typeof PedidosRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cardapio'
    | '/conta'
    | '/login'
    | '/pedido'
    | '/pedidos'
    | '/admin/cardapio'
    | '/admin/financeiro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cardapio'
    | '/conta'
    | '/login'
    | '/pedido'
    | '/pedidos'
    | '/admin/cardapio'
    | '/admin/financeiro'
  id:
    | '__root__'
    | '/'
    | '/cardapio'
    | '/conta'
    | '/login'
    | '/pedido'
    | '/pedidos'
    | '/admin/cardapio'
    | '/admin/financeiro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardapioRoute: typeof CardapioRoute
  ContaRoute: typeof ContaRoute
  LoginRoute: typeof LoginRoute
  PedidoRoute: typeof PedidoRoute
  PedidosRoute: typeof PedidosRoute
  AdminCardapioRoute: typeof AdminCardapioRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido': {
      id: '/pedido'
      path: '/pedido'
      fullPath: '/pedido'
      preLoaderRoute: typeof PedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio': {
      id: '/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof CardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/admin/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cardapio': {
      id: '/admin/cardapio'
      path: '/admin/cardapio'
      fullPath: '/admin/cardapio'
      preLoaderRoute: typeof AdminCardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardapioRoute: CardapioRoute,
  ContaRoute: ContaRoute,
  LoginRoute: LoginRoute,
  PedidoRoute: PedidoRoute,
  PedidosRoute: PedidosRoute,
  AdminCardapioRoute: AdminCardapioRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
